Updates to use switcheroo-control to get dual GPU information
elementary/switchboard-plug-about pull request #141
Opened 2020-10-21 04:25 UTC by jhaygood86

This switches to using switcheroo-control to get dual GPU information.

Note: switcheroo-control is already packaged by Ubuntu, but not installed by default on elementary OS 6.0. This package will need to depend on that. I am also going to work on updating the Application Menu to use the package details to support the Launch on Dedicated/Integrated Card feature like GNOME 3.38 has (which uses a setting in the .desktop file to determine if it should default to the Integrated or Dedicated card, and uses a context menu to give the user to option use a different GPU)

To be fully useful on NVIDIA systems, we will need to make sure NVIDIA proprietary kernel is installed AND prime-select is set to on-demand (i.e., use hybrid graphics)

2020-10-21 04:33 UTC, jhaygood86 commented
![Screenshot from 2020-10-21 00-07-29](https://user-images.githubusercontent.com/360393/96673699-13202400-1335-11eb-9c9e-ac44e0893a16.png)

Example screenshot on a Hybrid Graphics system

2020-11-11 14:25 UTC, andirsun commented
My nvidia mx 250 graphic card doesnt show properly name. Will this PR fix that ? 
![image](https://user-images.githubusercontent.com/22928302/98823173-c4c7e780-23ff-11eb-9fdd-499b799024dd.png)

2020-12-02 09:59 UTC, davidmhewitt requested changes
Looks good at a glance!

I've added one minor comment about the README.

I don't have any dual GPU machines to test. But I'll test on a few of my single GPU machines to check there are no regressions and get back to you.

2020-12-02 09:59 UTC, davidmhewitt commented on README.md
> +* switchboard-control (at runtime)
You mean `switcheroo-control` here, right?

2020-12-02 10:43 UTC, davidmhewitt requested changes
Additionally, I would prefer if we could keep the gnome-session code around as a fallback for getting the GPU info if switcheroo isn't working/installed.

2020-12-02 11:20 UTC, davidmhewitt requested changes

2020-12-02 11:20 UTC, davidmhewitt commented on src/Views/HardwareView.vala
> +    private string get_gpu_name (bool is_primary) {
The return type of this method needs to be marked as nullable with `string?` as returning `null` is a possibility with this method.

2021-01-19 11:53 UTC, davidmhewitt commented
@jhaygood86 Do you still have time to work on this? I'd be happy to take over and finish this branch off if you like?

2021-01-22 09:39 UTC, davidmhewitt commented
I reworked this branch and made some improvements and it has now been merged in https://github.com/elementary/switchboard-plug-about/commit/35102bb4189d34e2bd6b81485e8482dbc1fdc476

So I'll close this PR now. Thanks again for starting this, it's a big improvement!

2021-01-22 09:39 UTC, closed without merging