OperatingSystemView: display PRETTY_NAME when possible
elementary/switchboard-plug-about pull request #222
Opened 2021-07-23 04:43 UTC by bobby285271

Implementation of https://github.com/NixOS/nixpkgs/pull/130380#issuecomment-885147633.

`VERSION` in NixOS is a bit too long to display in the latest switchboard:

```
NAME=NixOS
ID=nixos
VERSION="21.11.git.165c18ade65 (Porcupine)"
VERSION_CODENAME=porcupine
VERSION_ID="21.11.git.165c18ade65"
PRETTY_NAME="NixOS 21.11 (Porcupine)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

It will be great if we can display `PRETTY_NAME` when `NAME` is a prefix of it so we can still make `NAME` bold.
The currently used `NAME` + `VERSION` way can be used as an alternative if the requirements are not satisfied.
See below screenshot for reference.

![](https://user-images.githubusercontent.com/20080233/126737794-49cf8c73-72f6-46c9-9033-f99eddc15460.png)

Thanks in advance in reviewing :-)

2021-07-23 16:43 UTC, danrabbit requested changes
Hey right on, thanks for working on this! Just a couple of inline comments

2021-07-23 16:43 UTC, danrabbit commented on src/Views/OperatingSystemView.vala
> +            && os_pretty_name.get(os_name.length) == ' ') {
Wouldn't [`has_prefix`](https://valadoc.org/glib-2.0/string.has_prefix.html) work for this?
```suggestion
            && os_pretty_name.has_prefix (os_name + " ") {
```

2021-07-23 16:43 UTC, danrabbit commented on src/Views/OperatingSystemView.vala
> +                os_pretty_name.slice(os_name.length, os_pretty_name.length)
elementary code style is to use spaces before parentheses :) 
```suggestion
                os_pretty_name.slice (os_name.length, os_pretty_name.length)
```

2021-07-24 01:13 UTC, bobby285271 commented
> Hey right on, thanks for working on this! Just a couple of inline comments

Just did the update, please take a look, thanks!

2021-08-02 21:14 UTC, davidak commented
This is not needed anymore for NixOS with https://github.com/NixOS/nixpkgs/pull/131967. The `VERSION` is now only the release number.

If it's not an issue with other distros, this can get closed.

2021-08-08 21:54 UTC, cassidyjames commented
This looks clean enough and may be nice, but if it's not required for NixOS anymore, I'm also fine closing it. We can always re-open it or something like it if there's a specific downstream request.

2021-08-08 21:54 UTC, closed without merging