Better memory and storage info
elementary/switchboard-plug-about pull request #251
Opened 2022-10-01 16:54 UTC by vjr

Stolen code from GNOME settings repo to use UDev and UDisks libraries to get more accurate memory and storage info.

Memory now shows the physical RAM capacity and storage code collects the total size of all non-removable and non-ejectable disks.

Before: (note the non-physical RAM size using glibtop.mem library and storage size of the root partition only)

![about_before2](https://user-images.githubusercontent.com/612302/193419738-8fa07bc7-22b1-4f21-a7be-4a9c6792e73f.png)

After: (note the more accurate physical RAM size and storage size of the physical disk)

![about_after2](https://user-images.githubusercontent.com/612302/193419741-bc8e39b6-b536-4c5d-8dbc-73f4ea1047f1.png)

2022-10-01 17:00 UTC, vjr commented
I'm not sure how to fix the missing dependency error in the build stages... @elementary/desktop-developers

2022-10-01 17:20 UTC, vjr commented
Here's what it looks like on my laptop - notice the disk size isn't rounded off but still acceptable IMO.

Before:

![about_before](https://user-images.githubusercontent.com/612302/193420854-4703b117-e1e7-4f7f-959e-56655736992b.png)

After:

![about_after](https://user-images.githubusercontent.com/612302/193420856-9587306b-0756-4038-9e27-7b847a896d1c.png)

2022-10-04 06:04 UTC, zeebok commented
> I'm not sure how to fix the missing dependency error in the build stages... @elementary/desktop-developers

I believe you need to add those dependencies to the github workflow yml files

2022-10-04 06:43 UTC, tintou requested changes

2022-10-04 06:46 UTC, vjr commented on src/Views/HardwareView.vala
> +            foreach (var object in client.object_manager.get_objects ()) {
Addressed, thank you!

2022-10-04 06:47 UTC, tintou approved these changes

2022-10-04 06:48 UTC, merged